const express = require('express')
const connectToLnNode = require('@radar/lnrpc')

async function start () {
  const app = express()

  try {
    const lnRpc = await connectToLnNode({
      server: 'localhost:10009', // 10009 is the GRPC port
      tls: './tls.cert', // Generated by LND
      macaroonPath: './admin.macaroon' // Generated by LND
    })
    console.log('LND info:', await lnRpc.getInfo())
  } catch (e) {
    console.log(e)
  }
  // app.get('/data', async (req, res) => {
  //   res.send('You need to pay first')
  // })

  // app.listen(8000)
}

start().then(() => console.log('Listening on :8000'))
